title: Significant Factors That Contribute The Success Of A Movie
logo: <img src="/assets/img/awards.png" width="250" height="180">
description: Create by Yuhao Sun, Yu Wang.
show_downloads: false
repository: https://github.com/MUSA-550-Fall-2022/the-success-of-a-movie/
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
